import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>

        <nav className="flex justify-around">
          <div className="flex">
            <img src="./Assets/Group9.svg" alt="logo" />
            <h1 className="mt-14 ms-4 text-3xl font-bold font-['Lemon Milk']">TECKVION</h1>
          </div>

          <div className="flex text-xl mt-10 font-['Montserrat'] font-bold">
            <div>
              <h1 className="me-5">HOME</h1>
              <div className="mb-10 w-14 h-1 bg-fuchsia-700" />
            </div>

            <h1 className="me-5">PROJECTS</h1>
            <span className="flex me-5">
              <h1>SERVICES</h1>
              <img className="mb-10" src="./Assets/Polygon 1.svg" alt="logo" />
            </span>
            <h1 className="me-5">COURSES</h1>
            <h1 className="me-5">ABOUT US</h1>
            <h1 className="me-5">OPPORTUNITIES</h1>

            <img className="ms-5 mb-10" src="./Assets/search icon.svg" alt="" />
          </div>
        </nav>

        {children}

        <footer className="flex justify-evenly mt-32 mb-16 font-['Montserrat']">

          <div>
            <h1 className="text-xl font-semibold">About Us</h1>
            <p className="mt-4">Who we are</p>
            <p className="mt-4">Our partners</p>
            <p className="mt-4">Become a partner</p>
          </div>

          <div className="mt-auto mb-auto">
            <p className="">Meet our staff</p>
            <p className="mt-4">Opportunities</p>
          </div>

          <div>
            <h1 className="text-xl font-semibold">Help & Support</h1>
            <p className="mt-4">FAQs</p>
            <p className="mt-4">Cookie policy</p>
            <p className="mt-4">Terms of service</p>
          </div>

          <div className="mt-auto mb-auto">
            <p>Contact us</p>
            <p className="mt-4">Get the app</p>
          </div>

          <div className="mt-auto mb-auto">

            <div className="flex">
              <img className="me-6" src="./Assets/Vector (6).svg" alt="" />
              <img className="me-6" src="./Assets/Vector (2).svg" alt="" />
              <img className="me-6" src="./Assets/Vector (3).svg" alt="" />
              <img className="me-6" src="./Assets/Vector (4).svg" alt="" />
              <img className="me-6" src="./Assets/Vector (5).svg" alt="" />
              <img className="" src="./Assets/Group (2).svg" alt="" />
            </div>

            <div className="flex mt-5">
              <img className="" src="./Assets/Group 51.svg" alt="" />
              <p className="">Teckvion 2024</p>
            </div>

          </div>

        </footer>
      </body>
    </html>
  );
}
